apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    app: init
spec:
  initContainers:
  - name: install
    image: busybox
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://www.baidu.com
    volumeMounts:
    - name: workdir
      mountPath: /work-dir  # /work-dir目录，包括index.html和workdir卷相映射
  containers:
  - name: main-nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html  # /usr/share/nginx/html目录也和workdir卷相映射
  volumes:
  - name: workdir
    emptyDir: {}  # 表示一个临时卷