apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-pvc-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nfs-pvc
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          subPath: nginxpvc-test
          mountPath: /usr/share/nginx/html  # nginx根目录与pvc绑定，pvc-nfs2对应的nfs的共享目录
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs2

# 为了方便外部访问创建一个NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-pvc
  labels:
    app: nfs-pvc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web
  selector:
    app: nfs-pvc