apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
spec:
  selector:
    app: nginx
  type: NodePort  # Service的类型是NodePort
  ports:
  - name: nodeport-demo-http
    protocol: TCP
    port: 80
    targetPort: nginxweb
    nodePort: 30001  # 集群中的所有Node节点都会分配到开启这样的端口，不指定的话也会自动生成一个端口