apiVersion: v1
kind: Pod
metadata:
  name: secret-pod2
spec:
  containers:
  - name: secret-pod2
    image: busybox
    command: ["/bin/sh", "-c", "cat /etc/secrets/username"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  volumes:
  - name: secrets  # 要与volumeMounts中的name一致进行映射
    secret:
      secretName: secret-demo1