apiVersion: v1
kind: Pod
metadata:
  name: secret-pod1
spec:
  containers:
  - name: secret-pod1
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-demo1
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-demo1
          key: password