apiVersion: v1
kind: Pod
metadata:
  name: testcm1
spec:
  containers:
  - name: testcm1
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "env"
    env:  # 第一种配置方法
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: cm-demo4
          key: db.host
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: cm-demo4
          key: db.port
    envFrom:  # 第二种配置方法
    - configMapRef:
        name: cm-demo1