apiVersion: v1
kind: Pod
metadata:
  name: testcm2
spec:
  containers:
  - name: testcm2
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "echo $(DB_HOST) $(DB_PORT)"
    env:  # 第一种配置方法
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: cm-demo4
          key: db.host
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: cm-demo4
          key: db.port