apiVersion: v1
kind: Pod
metadata:
  name: testcm4
spec:
  containers:
  - name: testcm4
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "cat /etc/config/path/to/redis.conf"  # 新增了路径 path/to
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: cm-demo3
      items:
      - key: redis.conf  # 手动指定加载config的key和path
        path: path/to/redis.conf