apiVersion: v1
kind: Pod
metadata:
  name: testcm3
spec:
  containers:
  - name: testcm3
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "cat /etc/config/redis.conf"  # cm-demo3中的key与文件名对应
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume  # 需要与volumeMounts里的name一致
    configMap:
      name: cm-demo3